// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"awesomeProject/app/controllers"
	"awesomeProject/app/repository"
	"awesomeProject/app/service"
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitDependencies() *Initialization {
	gormDB := ConnectToDB()
	userRepositoryImpl := repository.UserRepositoryInit(gormDB)
	authRepositoryImpl := repository.AuthRepositoryInit(gormDB)
	orderRepositoryImpl := repository.OrderRepositoryInit(gormDB)
	userServiceImpl := service.UserServiceInit(userRepositoryImpl)
	authServiceImpl := service.AuthServiceInit(authRepositoryImpl)
	orderServiceImpl := service.OrderServiceInit(orderRepositoryImpl)
	userControllerImpl := controllers.UserControllerInit(userServiceImpl)
	authControllerImpl := controllers.AuthControllerInit(authServiceImpl)
	orderControllerImpl := controllers.OrderControllerInit(orderServiceImpl)
	initialization := NewInitialization(userRepositoryImpl, authRepositoryImpl, orderRepositoryImpl, userServiceImpl, authServiceImpl, orderServiceImpl, userControllerImpl, authControllerImpl, orderControllerImpl)
	return initialization
}

// injector.go:

var db = wire.NewSet(ConnectToDB)

var userServiceSet = wire.NewSet(service.UserServiceInit, wire.Bind(new(service.UserService), new(*service.UserServiceImpl)))

var userRepoSet = wire.NewSet(repository.UserRepositoryInit, wire.Bind(new(repository.UserRepository), new(*repository.UserRepositoryImpl)))

var userCtrlSet = wire.NewSet(controllers.UserControllerInit, wire.Bind(new(controllers.UserController), new(*controllers.UserControllerImpl)))

var authServiceSet = wire.NewSet(service.AuthServiceInit, wire.Bind(new(service.AuthService), new(*service.AuthServiceImpl)))

var authRepoSet = wire.NewSet(repository.AuthRepositoryInit, wire.Bind(new(repository.AuthRepository), new(*repository.AuthRepositoryImpl)))

var authCtrlSet = wire.NewSet(controllers.AuthControllerInit, wire.Bind(new(controllers.AuthController), new(*controllers.AuthControllerImpl)))
